name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./settings
          push: true
          tags: us.gcr.io/neural-passkey-248222/settings:${{ github.sha }}
      - uses: danielr1996/envsubst-action@1.0.0
        env:
          IMAGE: ${{ github.sha }}
        with:
          input: settings/deployment.yaml
          output: settings/deployment-final.yaml
      - name: kubectl - Google Cloud GKE cluster.
        uses: ameydev/gke-kubectl-action@master
        env:
          PROJECT_ID: neural-passkey-248222
          APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
          CLUSTER_NAME: devops-exploration
          ZONE_NAME: us-west3
        with:
          args: apply -f settings/deployment-final.yaml