name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - name: Login to gcloud registry
      #   id: gcloud
      #   uses: elgohr/gcloud-login-action@master
      #   with:
      #     account_key: ${{ secrets.GCP_SA_KEY }}
      # - name: Publish to Registry
      #   uses: elgohr/Publish-Docker-Github-Action@master
      #   with:
      #     name: ${{ secrets.GCP_PROJECT_ID }}/settings
      #     username: ${{ steps.gcloud.outputs.username }}
      #     password: ${{ steps.gcloud.outputs.password }}
      #     registry: us.gcr.io
      # - name: Set up Cloud SDK
      #   uses: google-github-actions/setup-gcloud@master
      #   with:
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}
      #     service_account_key: ${{ secrets.GCP_SA_KEY }}
      #     export_default_credentials: true
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: us.gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./settings
          push: true
          tags: us.gcr.io/neural-passkey-248222/settings:latest